# Style guide: https://rubystyle.guide
# Config docs: https://docs.rubocop.org
# Config: https://github.com/rubocop/rubocop/blob/master/config/default.yml

---
plugins:
  - rubocop-minitest
  - rubocop-ordered_methods
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.3

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false
